accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login', kwargs={
       'template_name': 'accounts/login_form.html',
    }),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={
        'next_page': '/',
    }),
    url(r'^signup/$',  views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile')
]

baemin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'(?P<shop_id>\d+)/new/$', views.order_new, name='order_new'),
]

final/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^baemin/', include('baemin.urls', namespace='baemin')),
    url(r'^$', lambda r: redirect('baemin:index'), name='root'),
]

baemin/models.py
from django.conf import settings
from django.db import models


class Shop(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    addr = models.CharField(max_length=100)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Item(models.Model):
    shop = models.ForeignKey(Shop)
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Order(models.Model):
    shop = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    item_set = models.ManyToManyField(Item)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    @property
    def total(self):
        return sum(item.price for item in self.item_set.all())

baemin/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    def __init__(self, shop, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_set'].queryset = self.fields['item_set'].queryset.filter(shop=shop)

    class Meta:
        model = Order
        fields = ('item_set',)

accounts/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

baemin/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Shop
from .forms import OrderForm


def index(request):
    return render(request, 'baemin/index.html', {
        'shop_list': Shop.objects.all(),
    })


@login_required
def order_new(request, shop_id):
    shop = get_object_or_404(Shop, id=shop_id)
    if request.method == 'POST':
        form = OrderForm(shop, request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.shop = shop
            order.save()
            form.save_m2m()
            return redirect('profile')
    else:
        form = OrderForm(shop)
    return render(request, 'baemin/order_form.html', {
        'form': form,
        'shop': shop,
    })

accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html"  %}

{% block content %}
    <h3>Login</h3>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
<h3>{{ user }}'s Profile</h3>

<h4>주문내역</h4>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>가게명</th>
        <th>주문상품</th>
        <th>총액</th>
        <th>주문일시</th>
    </tr>
    </thead>
    <tbody>
    {% for order in user.order_set.all %}
    <tr>
        <td>{{ order.shop.name }}</td>
        <td>
            {% for item in order.item_set.all %}
            {{ item.name }}
            {% endfor %}
        </td>
        <td>{{ order.total }}</td>
        <td>{{ order.created_at }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html"  %}

{% block content %}
    <h3>Signup</h3>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{
            <form action="" class="as_t"></form>able }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

baemin/templates/baemin/index.html
{% extends "baemin/layout.html" %}

{% block content %}
<h3>가게목록</h3>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>가게명</th>
        <th>전화번호</th>
        <th>주소</th>
        <th>주문하기</th>
    </tr>
    </thead>
    <tbody>
    {% for shop in shop_list %}
        <tr>
            <td>{{ shop.name }}</td>
            <td>{{ shop.tel }}</td>
            <td>{{ shop.addr }}</td>
            <td><a href="{% url 'baemin:order_new' shop.id %}" class="btn btn-primary">주문하기</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

baemin/templates/baemin/layout.html
{% extends "layout.html" %}

baemin/templates/baemin/order_form.html
{% extends "baemin/layout.html" %}

{% block content %}
    <h3>{{ shop.name }} 주문</h3>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

final/templates/layout.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>배민 따라하기</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <a href="{% url 'root' %}">Home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">프로필</a>
            <a href="{% url 'logout' %}?next={{ reques.path }}  ">로그아웃</a>
        {% else %}
            <a href="{% url 'login' %}?next={{ reques.path }}">로그인</a>
            <a href="{% url 'signup' %}">회원가입</a>
        {% endif %}
        <hr/>

        {% block content %}
        {% endblock %}
    </body>
</html>